### ISSUE TITLE
About the test dataset accuracy

### ISSUE THREAD

**Issue by kitaharasetusna** [zeyuanyin/tiny-imagenet#1]
Hi! Thanks for your work! However, when I load your model and test it on the validation test and test dataset, the main task accuracy is extremely low (0.58%), but the training accuracy is proper (89.7%) for resnet-18 with 200 rounds. Do you have any clues?
I have checked the evaluation functions and all transforms. It's really weird.

**Comment by zeyuanyin** [comment]
Hi, I test your setting but can't reproduce your error case. Could you let me know if you followed the steps below?

1. download checkpoint:

```
wget https://huggingface.co/zeyuanyin/tiny-imagenet/resolve/main/rn18_200ep/checkpoint.pth
```

2. evaluation script:
```
torchrun --nproc_per_node=1 classification/train.py \
        --model 'resnet18' \
        --batch-size 256 \
        --test-only \
        --resume ./save/rn50_200ep/checkpoint.pth
```


3. output:

```
Test:   [ 0/40]  eta: 0:01:52  loss: 1.8256 (1.8256)  acc1: 57.8125 (57.8125)  acc5: 82.4219 (82.4219)  time: 2.8022  data: 0.9022  max mem: 1122
Test:  Total time: 0:00:04
Test:  Acc@1 60.470 Acc@5 81.070
```

**Comment by kitaharasetusna** [comment]
> Hi, I test your setting but can't reproduce your error case. Could you let me know if you followed the steps below?
> 
> 1. download checkpoint:
> 
> ```
> wget https://huggingface.co/zeyuanyin/tiny-imagenet/resolve/main/rn18_200ep/checkpoint.pth
> ```
> 
>  2. evaluation script:
> 
> ```
> torchrun --nproc_per_node=1 classification/train.py \
>         --model 'resnet18' \
>         --batch-size 256 \
>         --test-only \
>         --resume ./save/rn50_200ep/checkpoint.pth
> ```
> 
>  3. output:
> 
> ```
> Test:   [ 0/40]  eta: 0:01:52  loss: 1.8256 (1.8256)  acc1: 57.8125 (57.8125)  acc5: 82.4219 (82.4219)  time: 2.8022  data: 0.9022  max mem: 1122
> Test:  Total time: 0:00:04
> Test:  Acc@1 60.470 Acc@5 81.070
> ```

thanks! It's solved. It turns out there's something wrong with my data source. After downloading from your link. It works well. You can close this issue. Thanks again for your prompt response!
